export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  COMPOSITE_TIME_INVALID: "COMPOSITE_TIME_INVALID",
  COMPOSITE_SNAPSHOT_UNAVAILABLE: "COMPOSITE_SNAPSHOT_UNAVAILABLE",
  INDEXEDDB_UNAVAILABLE: "INDEXEDDB_UNAVAILABLE"
} as const;
